### ISSUE TITLE
De ce nu răspunde?

### ISSUE THREAD

**Issue by diridam27** [tacheometry/Agramat#10]
Acum ceva timp răspundea doar câteodată. Azi am scris nația mă-tii, nu a corectat în națiunea. Au scris 10 prieteni vroiam pe un server, nimic de la agramat. Unde suntem aici, în junglă?

**Comment by tacheometry** [comment]
Acum botul răspunde în DM-uri, și acest lucru poate fi schimbat de fiecare utilizator, după preferințe. M-am uitat la dexonline și „nația” pare corect, iar „vroiam” încă este corectat când trimit un mesaj. Poate Agramat nu are permisiune să citească canalul în care au fost trimise mesajele? Sau membrii au DM-urile oprite?

**Comment by diridam27** [comment]
<img width="442" alt="image" src="https://github.com/tacheometry/Agramat/assets/80452570/95c49186-4435-4323-afe5-46c72a4af7c2">
Așa este, aveam discord pe dnd și mi-a trimis în DM. Server-ul e OKPR, pe care ești, na
